"use client";

import React from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import {
  CheckCircle,
  XCircle,
  Video,
  ExternalLink,
  Calendar,
  Sparkles,
  Award,
  Loader2,
  BookOpen,
} from "lucide-react";
import useFetch from "@/hooks/use-fetch";
import { respondToInvitation } from "@/actions/candidate";
import { toast } from "sonner";

export default function CallActions({ call }) {
  const router = useRouter();
  const { fn: fnRespond, loading } = useFetch(respondToInvitation);

  const handleResponse = async (decision) => {
    try {
      await fnRespond({ callId: call.id, decision });
      toast.success(
        decision === "accepted"
          ? "Invitation accepted! You can now start the AI Virtual Interview."
          : "Invitation declined successfully."
      );
      router.refresh();
    } catch (err) {
      // Error handled by useFetch
    }
  };

  const isPending = call.candidateDecision === "pending";
  const isAccepted = call.candidateDecision === "accepted";
  const isDeclined = call.candidateDecision === "declined";

  // 1. Pending Decision
  if (isPending) {
    return (
      <div className="flex flex-wrap items-center gap-3">
        <Button
          onClick={() => handleResponse("accepted")}
          disabled={loading}
          className="bg-[hsl(var(--success))] hover:bg-[hsl(142,71%,38%)] text-white gap-2 shadow-[0_0_20px_-5px_hsl(var(--success)/0.4)]"
        >
          {loading ? (
            <Loader2 className="h-4 w-4 animate-spin" />
          ) : (
            <CheckCircle className="h-4 w-4" />
          )}
          Accept Invitation
        </Button>
        <Button
          onClick={() => handleResponse("declined")}
          disabled={loading}
          variant="outline"
          className="border-red-500/30 text-red-400 hover:bg-red-500/10 hover:border-red-500/50 gap-2"
        >
          {loading ? (
            <Loader2 className="h-4 w-4 animate-spin" />
          ) : (
            <XCircle className="h-4 w-4" />
          )}
          Decline
        </Button>
      </div>
    );
  }

  // 2. Declined Decision
  if (isDeclined) {
    return (
      <div className="text-sm font-medium text-red-400/90 flex items-center gap-1.5 py-1">
        <XCircle className="h-4 w-4 shrink-0" />
        You have declined this interview invitation.
      </div>
    );
  }

  // 3. Accepted: Handle different pipeline statuses
  if (isAccepted) {
    // 3a. Selected
    if (call.status === "selected") {
      return (
        <Card className="bg-[hsl(var(--success))]/10 border-[hsl(var(--success))]/20 overflow-hidden">
          <CardContent className="p-5 flex items-start gap-4">
            <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[hsl(var(--success))]/25 border border-[hsl(var(--success))]/35 shrink-0">
              <Award className="h-5 w-5 text-[hsl(var(--success))]" />
            </div>
            <div className="space-y-1">
              <h4 className="text-base font-bold text-[hsl(var(--success))] tracking-tight">
                Offer / Final Selection! 🎉
              </h4>
              <p className="text-sm text-foreground/80 leading-relaxed">
                Congratulations! The recruiter has selected you for this position. They will be in touch with you shortly regarding the next steps.
              </p>
            </div>
          </CardContent>
        </Card>
      );
    }

    // 3b. Rejected (Show AI Growth Panel / Feedback)
    if (call.status === "rejected") {
      return (
        <Card className="bg-white/[0.02] border-white/[0.04] overflow-hidden">
          <CardContent className="p-5 space-y-4">
            <div className="flex items-start gap-4">
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-amber-400/10 border border-amber-400/20 shrink-0">
                <BookOpen className="h-5 w-5 text-amber-400" />
              </div>
              <div className="space-y-1">
                <h4 className="text-base font-bold text-amber-400 tracking-tight flex items-center gap-2">
                  AI Growth Console
                  <Sparkles className="h-3.5 w-3.5 animate-pulse text-amber-400" />
                </h4>
                <p className="text-xs text-muted-foreground">
                  Constructive feedback generated by CareerPilot AI to boost your profile
                </p>
              </div>
            </div>

            {call.candidateFeedback ? (
              <div className="p-4 rounded-xl bg-white/[0.02] border border-white/[0.06] text-sm text-foreground/90 leading-relaxed whitespace-pre-line">
                {call.candidateFeedback}
              </div>
            ) : (
              <p className="text-sm text-muted-foreground italic">
                Application review finalized. Best wishes on your continued journey.
              </p>
            )}
          </CardContent>
        </Card>
      );
    }

    // 3c. Scheduled (Human Interview)
    if (call.status === "scheduled") {
      return (
        <Card className="bg-primary/10 border-primary/20 overflow-hidden">
          <CardContent className="p-5 space-y-4">
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
              <div className="flex items-start gap-4">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/20 border border-primary/30 shrink-0">
                  <Calendar className="h-5 w-5 text-primary" />
                </div>
                <div className="space-y-1">
                  <h4 className="text-base font-bold text-primary tracking-tight">
                    Human Interview Scheduled
                  </h4>
                  <p className="text-sm text-foreground/80 leading-relaxed">
                    Recruiter scheduled a live round for:{" "}
                    <span className="font-semibold text-foreground">
                      {call.scheduledAt
                        ? new Date(call.scheduledAt).toLocaleString()
                        : "To be confirmed"}
                    </span>
                  </p>
                </div>
              </div>

              {call.googleMeetLink && (
                <a
                  href={call.googleMeetLink}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="shrink-0"
                >
                  <Button className="gap-2">
                    <Video className="h-4 w-4" />
                    Join Google Meet
                    <ExternalLink className="h-3.5 w-3.5" />
                  </Button>
                </a>
              )}
            </div>

            {call.humanMessage && (
              <div className="p-4 rounded-xl bg-white/[0.02] border border-white/[0.06] text-sm text-foreground/80 leading-relaxed italic">
                "{call.humanMessage}"
              </div>
            )}
          </CardContent>
        </Card>
      );
    }

    // 3d. AI Virtual Interview Completed & Waiting for Recruiter Review / Shortlisting
    if (call.status === "under_ai_review" || call.status === "shortlisted") {
      return (
        <Card className="bg-primary/5 border-primary/20 overflow-hidden">
          <CardContent className="p-5 flex items-start gap-4">
            <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10 border border-primary/20 shrink-0">
              <CheckCircle className="h-5 w-5 text-primary animate-pulse" />
            </div>
            <div className="space-y-1">
              <h4 className="text-base font-bold text-primary tracking-tight">
                AI Virtual Interview Completed
              </h4>
              <p className="text-sm text-muted-foreground leading-relaxed">
                Your AI interview responses and video snapshot analysis have been compiled successfully. Your application is now **{call.status === "shortlisted" ? "shortlisted" : "under AI review"}** by the recruiter.
              </p>
            </div>
          </CardContent>
        </Card>
      );
    }

    // 3e. Accepted but not yet scheduled (Show Virtual Interview Button)
    return (
      <div className="flex flex-wrap items-center gap-3">
        <a href={`/live-interview?callId=${call.id}`}>
          <Button className="bg-gradient-to-r from-primary to-accent text-white gap-2 shadow-[0_0_20px_-5px_hsl(var(--primary)/0.4)]">
            <Video className="h-4 w-4" />
            Start AI Virtual Interview
          </Button>
        </a>
      </div>
    );
  }

  return null;
}
